### ISSUE TITLE
Troco.java - O valor inicializado no iterador está incorreto.

### ISSUE THREAD

**Issue by Zakonildo** [Zakonildo/Source-Code-Inspection#12]
Nome da   classe | Linha | Classificação / Tabela 2 | Descrição | Severidade
-- | -- | -- | -- | --
Troco.java | 65 | Computação | O valor inicializado no iterador está incorreto. | Médio

**Comment by Rubens-Mendes** [comment]
Valor corrigido no commit [acd45ed](https://github.com/Zakonildo/Source-Code-Inspection/commit/acd45ed7c00e2cae16028e366bf4115f6d4ac686).
