### ISSUE TITLE
Troco.java - A condição para sair do laço está errada.

### ISSUE THREAD

**Issue by Zakonildo** [Zakonildo/Source-Code-Inspection#13]
Nome da   classe | Linha | Classificação / Tabela 2 | Descrição | Severidade
-- | -- | -- | -- | --
Troco.java | 65 | Controle | A condição para sair do laço está errada. | Médio

**Comment by Rubens-Mendes** [comment]
Condição corrigida no commit [acd45ed](https://github.com/Zakonildo/Source-Code-Inspection/commit/acd45ed7c00e2cae16028e366bf4115f6d4ac686).
